package com.example.lenovo.mytestcode.db.greendao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.example.lenovo.mytestcode.bean.PlayProgress;
import com.example.lenovo.mytestcode.bean.Shop;
import com.example.lenovo.mytestcode.bean.User;

import com.example.lenovo.mytestcode.db.greendao.PlayProgressDao;
import com.example.lenovo.mytestcode.db.greendao.ShopDao;
import com.example.lenovo.mytestcode.db.greendao.UserDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig playProgressDaoConfig;
    private final DaoConfig shopDaoConfig;
    private final DaoConfig userDaoConfig;

    private final PlayProgressDao playProgressDao;
    private final ShopDao shopDao;
    private final UserDao userDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        playProgressDaoConfig = daoConfigMap.get(PlayProgressDao.class).clone();
        playProgressDaoConfig.initIdentityScope(type);

        shopDaoConfig = daoConfigMap.get(ShopDao.class).clone();
        shopDaoConfig.initIdentityScope(type);

        userDaoConfig = daoConfigMap.get(UserDao.class).clone();
        userDaoConfig.initIdentityScope(type);

        playProgressDao = new PlayProgressDao(playProgressDaoConfig, this);
        shopDao = new ShopDao(shopDaoConfig, this);
        userDao = new UserDao(userDaoConfig, this);

        registerDao(PlayProgress.class, playProgressDao);
        registerDao(Shop.class, shopDao);
        registerDao(User.class, userDao);
    }
    
    public void clear() {
        playProgressDaoConfig.clearIdentityScope();
        shopDaoConfig.clearIdentityScope();
        userDaoConfig.clearIdentityScope();
    }

    public PlayProgressDao getPlayProgressDao() {
        return playProgressDao;
    }

    public ShopDao getShopDao() {
        return shopDao;
    }

    public UserDao getUserDao() {
        return userDao;
    }

}
