/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_lenovo_mytestcode_utils_NdkTestUtils */

#ifndef _Included_com_example_lenovo_mytestcode_utils_NdkTestUtils
#define _Included_com_example_lenovo_mytestcode_utils_NdkTestUtils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_lenovo_mytestcode_utils_NdkTestUtils
 * Method:    getStringFromC
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_lenovo_mytestcode_utils_NdkTestUtils_getStringFromC
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
